### ISSUE TITLE
Missing Cielos' table

### ISSUE THREAD

**Issue by wog24435** [igromanru/Dark-Souls-III-Cheat-Engine-Guide#1]
Cielos has also made a table with some very neat things. It's on page 11.

http://forum.cheatengine.org/viewtopic.php?p=5661561#5661561

**Comment by igromanru** [comment]
Thank for the hint. 
Added in fb32fd0b59badee8aee57c2ec01c320c1e9a9f6b

**Comment by igromanru** [comment]
Thank for the hint. 
Added in fb32fd0b59badee8aee57c2ec01c320c1e9a9f6b
