### ISSUE TITLE
Is there any way to change the hollowing?

### ISSUE THREAD

**Issue by SturmDesChaos** [igromanru/Dark-Souls-III-Cheat-Engine-Guide#16]

**Comment by igromanru** [comment]
You can change weapon Effect On Self to Hollowing Reversed and try it out

**Comment by SturmDesChaos** [comment]
Oh but I was looking for the character hollowing, since I don't have dark sigils (I can't get hollow lvl) and I want to try a hollow build

**Comment by igromanru** [comment]
I don't know. Just create a new character, use the table to create drop souls and use noclip for speedrun.
