### ISSUE TITLE
Ban review,

### ISSUE THREAD

**Issue by Lokoluna** [igromanru/Dark-Souls-III-Cheat-Engine-Guide#18]
Hi, this is .<͜ . From the discord a day ago, I was wondering if there are ever lifts, for bans? I like the discord channel, whether i get hacking info or not, it's a nice community to just talk and chat with other people who have hobbies like me.

**Comment by Lokoluna** [comment]
oh. ok.

**Comment by igromanru** [comment]
Sorry, but I'm not an admin or mod there and here is not the right place for it.
