### ISSUE TITLE
Boss Error: Demon Princes not an Option

### ISSUE THREAD

**Issue by PKMWM1** [igromanru/Dark-Souls-III-Cheat-Engine-Guide#19]
Demon Princes are not options in the bosses tab under world flags even though it stated in the changelog that the DLC bosses were added. Every other DLC boss is and Demon Princes are the only ones not present and I would like to re-battle them.

**Comment by igromanru** [comment]
No, it isn't in the current table and not in the changelog. It will be just release today.

**Comment by igromanru** [comment]
I'll take a look.

**Comment by PKMWM1** [comment]
Is this even being worked on? Many other world flags were added but this issue still hasn't been resolved.

**Comment by igromanru** [comment]
It will be added in the next release.
