### ISSUE TITLE
Any way to get unused weapons?

### ISSUE THREAD

**Issue by HadesSama94** [igromanru/Dark-Souls-III-Cheat-Engine-Guide#20]
Hi! I'm trying to use unused weapons (offline, just for fun), but item swap method seems not to work, I got a message of full inventory or something. There's is a way to get those? I tried with `009A6B40	Ancient Dragon Halberd` and a few others, and nothing =(

**Comment by igromanru** [comment]
It's impossible to spawn unused context. You can only switch the move set and model of your equipped weapon, but it's not visible online.
