### ISSUE TITLE
Red invaders 

### ISSUE THREAD

**Issue by lkabrerak** [igromanru/Dark-Souls-III-Cheat-Engine-Guide#31]
How to make the RED NPC invade in mode Offline? I would appreciate your help

**Comment by igromanru** [comment]
Do you want to spawn a NPC invader? Never heart of it. We don't have anything for it.

**Comment by AYELUS** [comment]
im having the same problem when the ce table is ative(injected in the game) the offline invasion that should happen in certain points like roderick in undead settlement  dos not happen, something in the table is blocking the story line invasions trigger
