### ISSUE TITLE
Ringed City + 3 rings

### ISSUE THREAD

**Issue by Kavez** [igromanru/Dark-Souls-III-Cheat-Engine-Guide#4]
I notice that the item IDs for the +3 rings from the ringed city are still not included

Chloranthy Ring+3 = 20004E2D

Covetous Gold Serpent Ring+3 = 20004FA9

Covetous Silver Serpent Ring+3 = 20004FB3

Havel's ring+3 = 20004E37

Ring of Favor+3 = 20004E41

Ring of Steel Protection+3 = 20004E4B

Wolf Ring+3 = 20004EE1

there.

**Comment by igromanru** [comment]
Thank you Kavez.
Rings are now in the list. 
46c5c97adc57d33973fee2d4e9bfa70af497a1ae

**Comment by Kavez** [comment]
Forgot one

Ring of the Evil Eye +3 = 20005071
