### ISSUE TITLE
Test Data item

### ISSUE THREAD

**Issue by sinanjugbf** [igromanru/Dark-Souls-III-Cheat-Engine-Guide#6]
I copied an item from the item swapper (sorceror robe) but I think I screwed up somewhere because it became a test data item when I picked it up. It turned into a blank ?Weapon+26 in my inventory and I can't discard it. Is there a way for me to remove this?

**Comment by igromanru** [comment]
Which ID have you tried?
I'm not sure if it's possible to delete an item in the inventory.
Restore your save backup or delete the character and make a new one.
You can also try to ask in the [forum](http://fearlessrevolution.com/viewtopic.php?f=4&t=205) for help.

**Comment by sinanjugbf** [comment]
I have no clue to be honest. I think I might've put in an extra character and it turned into the test data item. Is there no way to delete the item through CE?

**Comment by igromanru** [comment]
I'm not up to date with all possibilities in current table.
Ask at the forum. http://fearlessrevolution.com/viewtopic.php?f=4&t=205&start=240
But I would create a new char and make next time a backup of the save game before you testing something.

**Comment by sinanjugbf** [comment]
I'll check with the thread then, thanks!
