### ISSUE TITLE
bonfire lvl

### ISSUE THREAD

**Issue by Pricex3** [igromanru/Dark-Souls-III-Cheat-Engine-Guide#7]
Hellooooooooo

We can't change the lvl of bonfire...
It's annoying

Plz help

**Comment by igromanru** [comment]
What do you mean with bonfire level?
Ask in the forum for help: http://fearlessrevolution.com/viewtopic.php?f=4&t=205

**Comment by Pricex3** [comment]
u know, when you put a undead bone in a bonfire at Firelink shrine you increase its lvl.
This is that we can't modify (lvl of bonfire)

**Comment by igromanru** [comment]
Undead Bone Shard upgrades your Estus Flask not the bonfire.  
However, I need more information what exactly you are doing.

**Comment by Pricex3** [comment]
I just want to modify the lvl of estus flask, that's all

**Comment by igromanru** [comment]
Not at all. It's not safe. Spawning estus shards or undead bone shards can cause a softban.

**Comment by Pricex3** [comment]
Even offline ? I have cracked version (sorry)

**Comment by igromanru** [comment]
If the table works for you, in your version. Just spawn undead bone shards and estus shards and use them.

**Comment by Pricex3** [comment]
Yeah but i want to change to lvl 10 --> at lvl 3
Because is so cheat 
Sorry if u don"t understand me, my english is bad..

**Comment by igromanru** [comment]
AS far I know, there is no option to do this, sorry.

**Comment by Pricex3** [comment]
Ok thanks you !
Whose can i ask to add this option?

**Comment by igromanru** [comment]
You can try in the forum: http://fearlessrevolution.com/viewtopic.php?f=4&t=205  
But I don't think that somebody will add it, because it can cause a ban for normal version.

**Comment by igromanru** [comment]
Ok, I've found it. Try out Hero->Estus (never sued before)
