### ISSUE TITLE
CTD selecting Base or Attributes

### ISSUE THREAD

**Issue by MisterCreed** [igromanru/Dark-Souls-III-Cheat-Engine-Guide#78]
crashes when I select either [Base] or [Attributes]. The few other cheats I use work. I'm using an actual steam version. Fully updated, all expansions(don't know if that would matter). I play in offline mode. With steam in offline as well. Cheat Engine 6.7. Default CE settings that I know of.Any insight that you know of would be appreciated or any reason it may happen.

**Comment by MisterCreed** [comment]
Those 2 parts had "Hide Children When Deactivated" checked. So all the attributes and such wouldn't appear unless you put a check mark on [Attributes] which would cause the crash.

**Comment by igromanru** [comment]
Learn to read and use CE 6.6...
