### ISSUE TITLE
Godmode doesn't work to me

### ISSUE THREAD

**Issue by Dhenes** [igromanru/Dark-Souls-III-Cheat-Engine-Guide#80]
Freeze time works perfectly but invulnerability does not. I've tried to enable all possible options that relate to godmode but none of them seem to work. Am I missing a step somewhere?

**Comment by kudlajz** [comment]
@Dhenes Go to `Flags > Character flags` and set `No Hit`, `No Damage` and `Invulnerability` to 1 and freeze the value (check the box).
